sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kais120/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kais120/docker-react npm run test -- --coverage
