sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kais120/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kais120/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-625253211575"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
